apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: backups
  labels:
    app: timemachine
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: afp
      port: 548
      protocol: TCP
      targetPort: afp
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: ldaps
  selector:
    app: timemachine
  sessionAffinity: None