apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.122
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: client-udp
      port: 67
      protocol: UDP
      targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.122
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns
    - name: pihole-http
      port: 80
      protocol: TCP
      targetPort: pihole-http
    - name: pihole-https
      port: 443
      protocol: TCP
      targetPort: pihole-https
  selector:
    app: pihole
  sessionAffinity: None